---
- name: configure_filebeat | See if Default Config File
  lineinfile:
    path: "{{ filebeat_conf }}"
    line: "#output.logstash:"
    state: absent
  check_mode: true
  register: conf

- name: configure_filebeat | Configure Filebeat (Comment/Uncomment Required Fields)
  replace:
    path: "{{ filebeat_conf }}"
    mode: 0600
    owner: root
    group: root
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  loop:
    - { regex: "output.elasticsearch:", replace: "#output.elasticsearch" }
    - { regex: 'hosts: \["localhost:9200"]', replace: '#hosts: ["localhost:9200"]' }
    - { regex: "#output.logstash:", replace: "output.logstash:" }
    - { regex: '#hosts: \["localhost:5044"]', replace: 'hosts: ["{{ elk_ip }}:{{ beat_port}}"]'}
    - { regex: "#ilm.enabled: false", replace: "ilm.enabled: false" }
  when: (conf.changed) or (conf.failed)

- name: configure_filebeat | Enables the beat's module, templates, and dashboard
  command: "/usr/bin/filebeat modules enable system"
  changed_when: false

- name: configure_filebeat | Restart Filebeat
  service:
    name: filebeat
    state: restarted
  changed_when: false

- name: configure_filebeat | Start Filebeat
  service:
    name: filebeat
    state: started
    enabled: true
